export const TEAMS = ["CSK", "DC", "KKR", "MI", "PBKS", "RCB", "RR", "SRH"];

export const VENUES = [
  "Barabati Stadium",
  "Brabourne Stadium",
  "Buffalo Park",
  "De Beers Diamond Oval",
  "Dr DY Patil Sports Academy",
  "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium",
  "Dubai International Cricket Stadium",
  "Eden Gardens",
  "Feroz Shah Kotla",
  "Himachal Pradesh Cricket Association Stadium",
  "Holkar Cricket Stadium",
  "JSCA International Stadium Complex",
  "Kingsmead",
  "M Chinnaswamy Stadium",
  "MA Chidambaram Stadium, Chepauk",
  "New Wanderers Stadium",
  "Newlands",
  "OUTsurance Oval",
  "Punjab Cricket Association Stadium, Mohali",
  "Rajiv Gandhi International Stadium, Uppal",
  "Sardar Patel Stadium, Motera",
  "Sawai Mansingh Stadium",
  "Shaheed Veer Narayan Singh International Stadium",
  "Sharjah Cricket Stadium",
  "Sheikh Zayed Stadium",
  "St George's Park",
  "Subrata Roy Sahara Stadium",
  "SuperSport Park",
  "Vidarbha Cricket Association Stadium, Jamtha",
  "Wankhede Stadium",
];
